ingress-nginx:
  controller:
    nodeSelector:
      beta.kubernetes.io/os: linux
    autoscaling:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux